# -*- coding: utf-8 -*-
"""ml-m6-rfr.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZLKuu-cbBqHBqw30dg4Fe0b90p2yicbr
"""

#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#dataset 
dataset = pd.read_csv('Position_Salaries.csv')
x=dataset.iloc[:,1:-1].values
y=dataset.iloc[:,-1].values
#print(x)
#print(y)

#model
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 13, random_state = 0)
regressor.fit(x, y)
#predicing value
print(regressor.predict([[6.5]]))


#visualising the result
x_grid = np.arange(min(x), max(x), 0.01)
x_grid = x_grid.reshape((len(x_grid), 1))
plt.scatter(x, y, color = 'red')
plt.plot(x_grid, regressor.predict(x_grid), color = 'blue')
plt.title('Decision Tree Regression')
plt.xlabel('Position level')
plt.ylabel('Salary')
plt.show()