# -*- coding: utf-8 -*-
"""ML-1-SimpleLinearRegression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u09xs_XSOyJz7x818LalyFRiSFLOS0B_
"""

#template for datapreprocessing
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
dataset = pd.read_csv('Salary_Data.csv')
X=dataset.iloc[:,:-1].values
Y=dataset.iloc[:,-1].values
#print(X)
#print(Y)
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test= train_test_split(X, Y, test_size = 0.2, random_state = 1)
#print(X_train)
#print(X_test)
#print(Y_train)
#print(Y_test)



#model

#importing class
from sklearn.linear_model import LinearRegression
regressor= LinearRegression()#making obj
regressor.fit(X_train,Y_train)#training model

#prdict the values
y_predict= regressor.predict(X_test)
#print(y_predict)

#visulising traing set
plt.scatter(X_train, Y_train, color = 'red')
plt.plot(X_train, regressor.predict(X_train), color = 'blue')
plt.title('Salary vs Experience (Training set)')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.show()

#visulising test set
plt.scatter(X_test, Y_test, color = 'red')
plt.plot(X_train, regressor.predict(X_train), color = 'blue')
plt.title('Salary vs Experience (Test set)')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.show()