# -*- coding: utf-8 -*-
"""ML-ARL1-Apriori.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dnXnfcjEQwYgLaM370Tg9kPVQFNZCpw9
"""

#installing apyori and importing libraries
!pip install apyori
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


#dataset
dataset = pd.read_csv('Market_Basket_Optimisation.csv', header = None)
transactions = []
#for i in range(0, 7501):
#  temp=[]
#  for j in range(0,20):
#    temp.append(str(dataset.values[i,j]))
#  transactions.append(temp)
for i in range(0, 7501):
  transactions.append([str(dataset.values[i,j]) for j in range(0, 20)])
#print(transactions)


#creating model
#para depends upon problem!
from apyori import apriori
rules = apriori(transactions = transactions, min_support = 0.003, min_confidence = 0.2, min_lift = 3, min_length = 2, max_length = 2)


#output:


#simple output:
results = list(rules)
#print(results)


#welorganized output:
#stackoverflow!
def inspect(results):
  lhs         = [tuple(result[2][0][0])[0] for result in results]
  rhs         = [tuple(result[2][0][1])[0] for result in results]
  supports    = [result[1] for result in results]
  confidences = [result[2][0][2] for result in results]
  lifts       = [result[2][0][3] for result in results]
  return list(zip(lhs, rhs, supports, confidences, lifts))

resultsinDataFrame = pd.DataFrame(inspect(results), columns = ['Left Hand Side', 'Right Hand Side', 'Support', 'Confidence', 'Lift'])

#Displaying the results non sorted
#resultsinDataFrame

#Displaying the results sorted
resultsinDataFrame.nlargest(n = 10, columns = 'Lift')