# -*- coding: utf-8 -*-
"""ML-Clustering2-HC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JRL9vJkmI2AQ79-WvfLsOGDelKHQbvgL
"""

#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


#datset
dataset = pd.read_csv('Mall_Customers.csv')
x = dataset.iloc[:, [3, 4]].values
#print(x)


#creating dendogram
import scipy.cluster.hierarchy as sch
dendrogram = sch.dendrogram(sch.linkage(x, method = 'ward'))
plt.title('Dendrogram')
plt.xlabel('Customers')
plt.ylabel('Euclidean distances')
plt.show()


#creating a model
from sklearn.cluster import AgglomerativeClustering
HC = AgglomerativeClustering(n_clusters = 5, affinity = 'euclidean', linkage = 'ward')
y_HC = HC.fit_predict(x)


#visualising cluster
plt.scatter(x[y_HC == 0, 0], x[y_HC == 0, 1], s = 100, c = 'red', label = 'Cluster 1')
plt.scatter(x[y_HC == 1, 0], x[y_HC == 1, 1], s = 100, c = 'blue', label = 'Cluster 2')
plt.scatter(x[y_HC == 2, 0], x[y_HC == 2, 1], s = 100, c = 'green', label = 'Cluster 3')
plt.scatter(x[y_HC == 3, 0], x[y_HC == 3, 1], s = 100, c = 'cyan', label = 'Cluster 4')
plt.scatter(x[y_HC == 4, 0], x[y_HC == 4, 1], s = 100, c = 'magenta', label = 'Cluster 5')
plt.title('Clusters of customers')
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.legend()
plt.show()