# -*- coding: utf-8 -*-
"""ML-M4-SVR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tp64y2DZNwOPlq6GBhfaCxwxvN3Jlema
"""

#Importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
dataset=pd.read_csv('Position_Salaries.csv')
x=dataset.iloc[:,1:-1].values
y=dataset.iloc[:,-1].values
y=y.reshape(len(y),1)
#print(x)
#print(y)
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
sc_y=StandardScaler()
x=sc_x.fit_transform(x)
y=sc_y.fit_transform(y)
#print(x)
#print(y)


#creating SVR model
from sklearn.svm import SVR
regressor =SVR(kernel='rbf')
regressor.fit(x,y)


#predicting single value
#remember we done the feature scaling so before predicting... we also have to performe scaling on input too.
sc_ans=regressor.predict(sc_x.transform([[6.5]]))
#print(sc_ans)
ans=sc_y.inverse_transform(sc_ans)
#print(ans)



#visualising the svr model
plt.scatter(sc_x.inverse_transform(x), sc_y.inverse_transform(y), color = 'red')
plt.plot(sc_x.inverse_transform(x), sc_y.inverse_transform(regressor.predict(x)), color = 'blue')
plt.title('SVR')
plt.xlabel('Position level')
plt.ylabel('Salary')
plt.show()